// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// is_cross
bool is_cross(std::vector<double> segment0, std::vector<double> segment1);
RcppExport SEXP _Rose_is_cross(SEXP segment0SEXP, SEXP segment1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type segment0(segment0SEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type segment1(segment1SEXP);
    rcpp_result_gen = Rcpp::wrap(is_cross(segment0, segment1));
    return rcpp_result_gen;
END_RCPP
}
// get_intersection_of_lines
arma::vec get_intersection_of_lines(arma::vec line1_pointA, arma::vec line1_pointB, arma::vec line2_pointA, arma::vec line2_pointB);
RcppExport SEXP _Rose_get_intersection_of_lines(SEXP line1_pointASEXP, SEXP line1_pointBSEXP, SEXP line2_pointASEXP, SEXP line2_pointBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type line1_pointA(line1_pointASEXP);
    Rcpp::traits::input_parameter< arma::vec >::type line1_pointB(line1_pointBSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type line2_pointA(line2_pointASEXP);
    Rcpp::traits::input_parameter< arma::vec >::type line2_pointB(line2_pointBSEXP);
    rcpp_result_gen = Rcpp::wrap(get_intersection_of_lines(line1_pointA, line1_pointB, line2_pointA, line2_pointB));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Rose_is_cross", (DL_FUNC) &_Rose_is_cross, 2},
    {"_Rose_get_intersection_of_lines", (DL_FUNC) &_Rose_get_intersection_of_lines, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_Rose(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
